function [r_n,r_v,g_n,g_v,b_n,b_v] = rgb_mode(I_ori,I_GT)
%RGB_MODE-> returns the RGB color mode for normal skin and vitiligo
redchannel=I_GT(:,:,1);
greenchannel=I_GT(:,:,2);
bluechannel=I_GT(:,:,3);
vskin_region=redchannel>200&greenchannel>200&bluechannel>200;
nskin_region=(~vskin_region);
%normal skin
edges=linspace(0,255,51);
R_nskin=redchannel(nskin_region);
R=reshape(R_nskin,[],1);
G_nskin=greenchannel(nskin_region);
G=reshape(G_nskin,[],1);
B_nskin=bluechannel(nskin_region);
B=reshape(B_nskin,[],1);
hist_R=histogram(R,edges);
R_vector=hist_R.Values;
hist_G=histogram(G,edges);
G_vector=hist_G.Values;
hist_B=histogram(B,edges);
B_vector=hist_B.Values;
max_R=max(R_vector);
[row_rn,col_rn]=find(R_vector==max_R);
idx_R=col_rn(1,1);
r_n=(edges(idx_R)+edges(idx_R+1))/2;
max_G=max(G_vector);
[row_gn,col_gn]=find(G_vector==max_G);
idx_G=col_gn(1,1);
g_n=(edges(idx_G)+edges(idx_G+1))/2;
max_B=max(B_vector);
[row_bn,col_bn]=find(B_vector==max_B);
idx_B=col_bn(1,1);
b_n=(edges(idx_B)+edges(idx_B+1))/2;
% vitiligo skin
redchannel_n=I_ori(:,:,1);
greenchannel_n=I_ori(:,:,2);
bluechannel_n=I_ori(:,:,3);
R_vskin=redchannel_n(vskin_region);
R_V=reshape(R_vskin,[],1);
G_vskin=greenchannel_n(vskin_region);
G_V=reshape(G_vskin,[],1);
B_vskin=bluechannel_n(vskin_region);
B_V=reshape(B_vskin,[],1);
hist_R_V=histogram(R_V,edges);
R_vector_V=hist_R_V.Values;
hist_G_V=histogram(G_V,edges);
G_vector_V=hist_G_V.Values;
hist_B_V=histogram(B_V,edges);
B_vector_V=hist_B_V.Values;
max_R_V=max(R_vector_V);
[row_rv,col_rv]=find(R_vector_V==max_R_V);
idx_R_V=col_rv(1,1);
r_v=(edges(idx_R_V)+edges(idx_R_V+1))/2;
max_G_V=max(G_vector_V);
[row_gv,col_gv]=find(G_vector_V==max_G_V);
idx_G_V=col_gv(1,1);
g_v=(edges(idx_G_V)+edges(idx_G_V+1))/2;
max_B_V=max(B_vector_V);
[row_bv,col_bv]=find(B_vector_V==max_B_V);
idx_B_V=col_bv(1,1);
b_v=(edges(idx_B_V)+edges(idx_B_V+1))/2;
end

